# Generated by Django 5.1.7 on 2025-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("tagline", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("technology", models.CharField(max_length=250)),
                ("link", models.CharField(max_length=100, null=True)),
                ("gitlink", models.CharField(max_length=100, null=True)),
                ("image", models.FileField(blank=True, upload_to="projects/")),
            ],
        ),
    ]
