# Generated by Django 5.1.7 on 2025-03-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_contactmessage_alter_project_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
